In [16]:
import numpy as np
np.random.seed(42)

class sample(object):
  def __init__(self, X, n_subspace):
    self.idx_subspace = self.random_subspace(X, n_subspace)

  def __call__(self, X, y):
    idx_obj = self.bootstrap_sample(X)
    X_sampled, y_sampled = self.get_subsample(X, y, self.idx_subspace, idx_obj)
    return X_sampled, y_sampled

  @staticmethod
  def bootstrap_sample(X, random_state=42):
    # Генерация случайных индексов с возвращением (бутстрэп)
    indices = np.unique(np.random.choice(X.shape[0], X.shape[0]))
    return indices

  @staticmethod
  def random_subspace(X, n_subspace, random_state=42):
    n_features = X.shape[1]  # Количество признаков
    # Генерация случайных индексов подпространства признаков
    indices = np.sort(np.random.choice(n_features, n_subspace, replace=False))
    return indices

  @staticmethod
  def get_subsample(X, y, idx_subspace, idx_obj):
    x_sampled = X[idx_obj][:, idx_subspace]  # Получение подвыборки признаков
    y_sampled = y[idx_obj]  # Получение подвыборки целевых значений
    return x_sampled, y_sampled


## Пример формата входных и выходных данных

In [22]:
X = np.array([[1,2,3], [4,5,6], [7,8,9]])
Y = np.array([1, 2, 3])
s = sample(X, 2)

bootstrap_indices = s.bootstrap_sample(X)
X_sampled, y_sampled = s.get_subsample(X, Y, s.idx_subspace, bootstrap_indices)

In [23]:
# Строки, выбранные из исходного массива X
bootstrap_indices

array([0, 2])

In [24]:
# Столбцы, выбранные из исходного массива X
s.idx_subspace

array([0, 1])

In [25]:
# Матрица на выходе
X_sampled

array([[1, 2],
       [7, 8]])

In [26]:
# Вектор ответов на выходе
y_sampled

array([1, 3])